### ISSUE TITLE
Tower launches but doesn’t open repo unless Tower’s already running

### ISSUE THREAD

**Issue by mava** [jfieber/Tower.novaextension#2]
If Tower is not already running in the background, the extension only launches Tower, but the current Nova workspace doesn’t open in Tower. (When Tower is already running, everything works as expected.) I suspect that this has to do with some changes in the latest versions of Tower, because it used to work fine in the past. I’m currently running version 10.2.2.

**Comment by jfieber** [comment]
@mava Sorry for the slow response, but I believe I've fixed it in 3eb83de. I'm not exactly sure which Tower version broke it, but it was fairly recent.  Let me know if it fixes it for you.

**Comment by jfieber** [comment]
Whoops, the change made things worse, not better, as there was a hole in my testing. I've push a v1.3 that revers to the old (buggy) behavior pending a proper fix.

**Comment by jfieber** [comment]
@mava digging deeper, it seems that *all* ways of specifying a repository path to Tower fail if Tower isn't running. This is really a bug in Tower, and I've just filed a report with them.  I can imagine some workarounds, but they would be add complexity and potential fragility to the extension.

**Comment by mava** [comment]
Thank you for looking into this, @jfieber! Let’s hope that it gets fixed in Tower itself.

**Comment by jfieber** [comment]
@mava Confirmed, this is a bug known to them that will be addressed in an upcoming release.

**Comment by mava** [comment]
It’s already fixed in Tower 10.3 Beta. Yay! Sorry for bothering you about this. Let’s close this issue once they push the fix to a non-beta release, if that’s OK with you.

**Comment by jfieber** [comment]
Confirmed that Tower 10.3, now released, fixes the problem.
